# To use tox, see https://tox.readthedocs.io
# Simply pip or conda install tox
# then run `tox` or `tox -- {pytest args}`

# To rebuild the tox environment, for example when dependencies change, use
# `tox -r`

[tox]
envlist = py311-sphinx-latest

[testenv]
usedevelop = true

[testenv:py{310,311,312,313}-sphinx-{7,8,latest}]
deps =
    sphinx-7: sphinx>=7.2,<8
    sphinx-8: sphinx>=8,<9
extras =
    testing
commands = pytest {posargs}

[testenv:docs-sphinx-{7,8,latest}]
deps =
    sphinx-7: sphinx>=7.2,<8
    sphinx-8: sphinx>=8,<9
extras =
    docs
passenv =
    TERM
allowlist_externals = echo
commands_pre =
    python -c "import shutil; shutil.rmtree('docs/_build', ignore_errors=True)"
commands = sphinx-build -nW --keep-going -T {posargs} -b html docs/ docs/_build/html
commands_post =
    echo "open docs/_build/html/index.html"
